# Generated by Django 5.2.7 on 2026-04-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("WEB_APP", "Web Application"),
                            ("API", "API"),
                            ("MOBILE", "Mobile"),
                            ("NETWORK", "Network"),
                        ],
                        db_index=True,
                        default="WEB_APP",
                        max_length=20,
                        verbose_name="Asset Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "last_scan",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Scan"
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(default=0.0, verbose_name="Risk Score"),
                ),
                (
                    "technologies",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Technologies"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
