# Generated by Django 5.2.7 on 2026-04-20 14:21

import apps.users.managers.users
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.managers.users.UserManager()),
            ],
        ),
    ]
