# Generated by Django 5.2.7 on 2026-04-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_url",
                    models.URLField(max_length=500, verbose_name="Target URL"),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Scan"),
                            ("QUICK", "Quick Scan"),
                            ("API", "API Scan"),
                            ("OWASP", "OWASP Top 10"),
                            ("CUSTOM", "Custom Scan"),
                        ],
                        default="FULL",
                        max_length=20,
                        verbose_name="Scan Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="Progress (%)"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration"
                    ),
                ),
                (
                    "results_summary",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Results Summary"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan",
                "verbose_name_plural": "Scans",
                "db_table": "scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_url",
                    models.URLField(max_length=500, verbose_name="Target URL"),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Scan"),
                            ("QUICK", "Quick Scan"),
                            ("API", "API Scan"),
                            ("OWASP", "OWASP Top 10"),
                            ("CUSTOM", "Custom Scan"),
                        ],
                        default="FULL",
                        max_length=20,
                        verbose_name="Scan Type",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                ("next_run", models.DateTimeField(verbose_name="Next Run")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Schedule",
                "verbose_name_plural": "Scan Schedules",
                "db_table": "scan_schedules",
                "ordering": ["next_run"],
            },
        ),
    ]
