# Generated by Django 5.2.7 on 2026-04-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                (
                    "affected_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Affected URL",
                    ),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, default="", verbose_name="Evidence"),
                ),
                (
                    "remediation",
                    models.TextField(
                        blank=True, default="", verbose_name="Remediation"
                    ),
                ),
                (
                    "cvss_score",
                    models.FloatField(blank=True, null=True, verbose_name="CVSS Score"),
                ),
                (
                    "cve_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="CVE ID"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vulnerabilities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="scans.scan",
                        verbose_name="Scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability",
                "verbose_name_plural": "Vulnerabilities",
                "db_table": "vulnerabilities",
                "ordering": ["-created_at"],
            },
        ),
    ]
