server {
    listen 80;
    server_name api.example.com; # DigitalOcean'dagi domain yoki IP manzil

    # Ushbu server faqatgina Backend (Django) API uchun xizmat qiladi
    
    # ── API So'rovlari ──
    location /api/ {
        # Backend docker porti hostda (masalan 8000) joylanganda
        proxy_pass http://127.0.0.1:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ── Admin Panel ──
    location /admin/ {
        proxy_pass http://127.0.0.1:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_addrs_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ── Media va Static Fayllar (Admin dizayni va upload fayllar) ──
    location /static/ {
        # O'zingiz DigitalOcean serverdagi loyiha turgan manzilni o'zgartiring
        alias /var/www/sentinel/backend/assets/staticfiles/; 
    }

    location /media/ {
        alias /var/www/sentinel/backend/assets/media/;
    }

    # Qolgan barcha so'rovlar (frontend uchun adashib kelganlar) 404 berishi kerak
    location / {
        return 404;
    }
}
