import PageHeader from "@/components/shared/PageHeader";
import { FileText, Download, Shield, TrendingUp, AlertTriangle, CheckCircle } from "lucide-react";

const ExecutiveBriefPage = () => {
  return (
    <div>
      <PageHeader
        title="Executive Brief"
        description="Board-ready security posture summary for Q4 2023. Auto-generated by Sentinel AI."
        actions={
          <button className="flex items-center gap-2 bg-gradient-primary px-5 py-2.5 rounded-lg text-sm font-bold text-on-primary-fixed shadow-glow-primary hover:opacity-90 transition-all">
            <Download className="w-4 h-4" />
            Download PDF
          </button>
        }
      />

      {/* Report Header Card */}
      <div className="bg-surface-low rounded-xl p-8 border-ghost mb-8">
        <div className="flex items-start justify-between mb-6">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <FileText className="w-6 h-6 text-primary" />
              <h3 className="text-xl font-bold font-headline text-white">Security Posture Report</h3>
            </div>
            <p className="text-xs text-[hsl(215,15%,45%)]">Generated: October 28, 2023 • Period: Q4 2023</p>
          </div>
          <div className="text-right">
            <p className="text-5xl font-bold font-headline text-primary">A-</p>
            <p className="text-[10px] text-[hsl(215,15%,45%)] uppercase font-bold">Overall Grade</p>
          </div>
        </div>

        {/* KPIs */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Security Score", value: "94/100", icon: Shield, change: "+3 pts", changeColor: "text-primary" },
            { label: "Open Vulnerabilities", value: "42", icon: AlertTriangle, change: "-18%", changeColor: "text-primary" },
            { label: "Mean Remediation", value: "3.4 days", icon: TrendingUp, change: "-12%", changeColor: "text-primary" },
            { label: "Compliance", value: "92%", icon: CheckCircle, change: "+5%", changeColor: "text-primary" },
          ].map((kpi) => (
            <div key={kpi.label} className="bg-surface-container rounded-lg p-4">
              <kpi.icon className="w-4 h-4 text-primary mb-2" />
              <p className="text-2xl font-bold font-headline text-white">{kpi.value}</p>
              <p className="text-[10px] text-[hsl(215,15%,45%)] uppercase tracking-widest font-semibold mt-1">{kpi.label}</p>
              <p className={`text-xs font-bold mt-2 ${kpi.changeColor}`}>{kpi.change} vs last quarter</p>
            </div>
          ))}
        </div>
      </div>

      {/* Executive Summary Text */}
      <div className="grid grid-cols-12 gap-6 mb-8">
        <div className="col-span-12 lg:col-span-8 bg-surface-low rounded-xl p-8 border-ghost">
          <h3 className="font-bold font-headline text-primary text-lg mb-4">Executive Summary</h3>
          <div className="space-y-4 text-sm text-[hsl(215,15%,60%)] leading-relaxed">
            <p>
              During Q4 2023, Sentinel conducted <span className="text-white font-bold">1,284 automated scans</span> across 
              <span className="text-white font-bold"> 142 targets</span>, identifying 42 open vulnerabilities. The overall 
              security posture has improved by <span className="text-primary font-bold">3 points</span> compared to Q3, 
              bringing the infrastructure security score to 94/100.
            </p>
            <p>
              <span className="text-sentinel-error font-bold">Critical findings</span>: Two SQL injection vulnerabilities 
              were discovered in the authentication service (api.v-scan.prod). Both have been verified as exploitable and 
              require immediate remediation. One has been auto-patched by the AI Remediation Copilot.
            </p>
            <p>
              <span className="text-primary font-bold">Positive trends</span>: Mean time to remediation decreased from 
              3.9 days to 3.4 days (-12%). The AI-powered scanning engine detected threats 40% faster than the previous 
              quarter. SOC2 compliance adherence improved to 98.4%.
            </p>
            <p>
              <span className="text-sentinel-tertiary font-bold">Areas of concern</span>: PCI-DSS compliance shows 12 
              configuration drifts that need attention. The authentication service remains the primary attack surface with 
              62% of all critical findings concentrated in this component.
            </p>
          </div>
        </div>

        {/* Risk Distribution */}
        <div className="col-span-12 lg:col-span-4 bg-surface-low rounded-xl p-6 border-ghost">
          <h3 className="font-bold text-white mb-6">Risk Distribution</h3>
          <div className="space-y-4">
            {[
              { label: "Critical", count: 2, pct: "5%", color: "bg-sentinel-error", bar: "w-[5%]" },
              { label: "High", count: 8, pct: "19%", color: "bg-sentinel-tertiary", bar: "w-[19%]" },
              { label: "Medium", count: 18, pct: "43%", color: "bg-[hsl(35,90%,55%)]", bar: "w-[43%]" },
              { label: "Low", count: 14, pct: "33%", color: "bg-primary", bar: "w-[33%]" },
            ].map((r) => (
              <div key={r.label}>
                <div className="flex justify-between items-center mb-1">
                  <span className="text-sm text-on-surface font-medium">{r.label}</span>
                  <span className="text-xs text-[hsl(215,15%,50%)]">{r.count} ({r.pct})</span>
                </div>
                <div className="h-2 bg-surface-high rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${r.color} ${r.bar}`} />
                </div>
              </div>
            ))}
          </div>

          <div className="mt-8 pt-6 border-t border-[hsl(222,20%,12%,0.2)]">
            <h4 className="text-sm font-bold text-white mb-3">Top Recommendations</h4>
            <ol className="space-y-2 text-xs text-[hsl(215,15%,55%)]">
              <li className="flex gap-2"><span className="text-primary font-bold">1.</span> Patch SQLi in auth endpoint immediately</li>
              <li className="flex gap-2"><span className="text-primary font-bold">2.</span> Address PCI-DSS configuration drifts</li>
              <li className="flex gap-2"><span className="text-primary font-bold">3.</span> Enable CSP headers across all services</li>
              <li className="flex gap-2"><span className="text-primary font-bold">4.</span> Review IoT gateway security controls</li>
            </ol>
          </div>
        </div>
      </div>

      {/* Compliance Matrix */}
      <div className="bg-surface-low rounded-xl p-6 border-ghost">
        <h3 className="font-bold text-white mb-4">Compliance Status Matrix</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { framework: "SOC2 Type II", status: "98.4%", statusLabel: "Compliant", color: "text-primary", bg: "bg-primary/10" },
            { framework: "PCI-DSS v4.0", status: "84%", statusLabel: "12 Drifts", color: "text-sentinel-tertiary", bg: "bg-sentinel-tertiary/10" },
            { framework: "HIPAA", status: "Pending", statusLabel: "Audit Scheduled", color: "text-[hsl(215,15%,55%)]", bg: "bg-surface-high" },
          ].map((c) => (
            <div key={c.framework} className="bg-surface-container rounded-lg p-5 flex justify-between items-center">
              <div>
                <h4 className="text-sm font-bold text-on-surface">{c.framework}</h4>
                <p className="text-xs text-[hsl(215,15%,45%)]">{c.statusLabel}</p>
              </div>
              <span className={`px-3 py-1 rounded-lg text-sm font-bold ${c.color} ${c.bg}`}>{c.status}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ExecutiveBriefPage;
